spring.application.name=spring-learn-country

server.port=8083
server.servlet.context-path=/

logging.level.root=INFO
logging.level.com.cognizant.springlearn=DEBUG
logging.level.com.cognizant.springlearn.service=DEBUG
logging.level.com.cognizant.springlearn.controller=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/spring-learn-country.log

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

server.connection-timeout=20000

server.tomcat.max-threads=200
server.tomcat.min-spare-threads=10

spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2000

spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non-null
