CREATE TABLE AuditLog (

    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    TransactionID NUMBER,

    AccountID NUMBER,

    Amount NUMBER,

    TransactionDate DATE,

    Action VARCHAR2(50)

);